### ISSUE TITLE
Pandoc CSS affects Atom GUI

### ISSUE THREAD

**Issue by fiapps** [atom-community/markdown-preview-plus#207]
I was experiencing some weird issues with the Atom GUI when I opened the Markdown preview. This turns out to be because the GUI is being styled by the custom CSS I'm using with pandoc (`--css=/home/me/custom.css` specified in Pandoc Options: Commandline Arguments). My CSS contained this:

``` css
body {
    font-family: Cardo, serif;
    font-size: 16px;
    line-height: 22px;
    color: #737373;
    background-color: white;
    margin: 10px 13px 10px 13px;
}
@media screen and (min-width: 914px) {
    body {
        width: 854px;
        margin:10px auto;
    }
}
```

Now, at least the second of these is useless when previewing in Atom, so I've commented them out for now, but until I did, they were doing strange things to the GUI: once the Atom window was 914px or wider, all of the tabs would be inside an 854px wide block surrounded by broad white margins. If I opened the Atom Settings, it would pick up the large font size that the CSS was trying to apply to the preview. Even now, headings in the Settings tab pick up the font I set in the CSS for `h1, h2, h3, h4, h5, h6`.
