### ISSUE TITLE
Sliders for code blocks remain when converting to PDF

### ISSUE THREAD

**Issue by jamesku1996** [atom-community/markdown-preview-plus#388]
![bar](https://imgur.com/xfzIUly.png)
As shown in the picture, after converting markdown to a PDF file, it seems that sliders for codeblocks remain there, but in a PDF file, you can't move that slider, so you can only see a portion of the code. The remaining of the code that's outside the range of the block is being cut out and you can never see it. Hope this can be fixed soon.

**Comment by lierdakil** [comment]
Hi! Thanks for reporting!

This is an oversight and can be fixed with some simple CSS. You can add this to your Atom stylesheet (Edit -> Stylesheet... menu item) if you need this working ASAP:
```less
  @media print {
    atom-text-editor {
      overflow: visible !important;
      .line {
        white-space: pre-wrap !important;
      }
    }
  }
```

I'll try to release a fix soon.
