### ISSUE TITLE
Empty lines in code blocks dissapper

### ISSUE THREAD

**Issue by kiwi0fruit** [atom-community/markdown-preview-plus#398]
Empty lines in code blocks dissapper in Atom preview. But in exported HTML they are present.

**Comment by lierdakil** [comment]
The issue is due to empty line-divs collapsing. A bit hacky, but effective way to fix this is to add a zero-width space to each line via
```css
atom-text-editor .line::before {
    content: "\200b";
}
```
You can add this to your stylesheet until the fix is released.
