### ISSUE TITLE
Support --citeproc in pandoc

### ISSUE THREAD

**Issue by pbsds** [atom-community/markdown-preview-plus#530]
`pandoc-citeproc` has been deprecated and removed in favor of the built-in flag [`--citeproc`](https://pandoc.org/MANUAL.html#citation-rendering).
This option is to my knowledge currently not possible to pass in to pandoc in `markdown-preview-plus`.

# Suggested fix:

Either perform a version detection on pandoc and use `--citeproc` or `-F pandoc-citeproc` accordingly, or simply add a new option to use `--citeproc` instead.

**Comment by pbsds** [comment]
Current workaround:

```yaml
# defaults.yaml, loaded with --defaults defaults.yaml
filters:
- type: citeproc
```

This has the side-effect of the preview not working if a defaults.yaml file is not present
